name: Build KIE Editors Standalone

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm ci

      - name: Build entire monorepo
        run: npm run build:prod

      - name: Upload kie-editors-standalone dist
        uses: actions/upload-artifact@v3
        with:
          name: kie-editors-standalone-dist
          path: packages/kie-editors-standalone/dist
