name: KIE Tools Production Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 22 + pnpm 9.3.0
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@9.3.0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Go 1.23.8
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.8

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Maven 3.9.6
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: '3.9.6'

      - name: Setup Helm 3.13.3
        run: |
          curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
          tar -zxvf helm.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Bootstrap dependencies
        run: pnpm bootstrap

      - name: Build all packages for production
        run: pnpm -r build:prod

      - name: Upload BPMN Editor (optional)
        uses: actions/upload-artifact@v3
        with:
          name: kie-editors-standalone-dist
          path: packages/kie-editors-standalone/dist
