name: Build KIE Editors Standalone

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9.3.0

    - name: Install dependencies
      run: |
        pnpm install -r --filter scripts...
        pnpm -F scripts/run-script-if run build
        pnpm -F scripts/build-env run build
        pnpm install --no-frozen-lockfile
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

    - name: Build standalone editors
      run: pnpm build:standalone

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kie-editors-dist
        path: packages/kie-editors-standalone/dist/
